//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberShoppe.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int Customer_Id { get; set; }

        [Required(ErrorMessage = "Full Name is Required")]
        [RegularExpression(@"^[a-zA-Z ]+$", ErrorMessage = "Full Name should contain alphabets only")]
        public string Full_Name { get; set; }

        [Required(ErrorMessage = "Email is Required")]
        [RegularExpression(@"[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}$", ErrorMessage = "Email Id should be in proper format.")]
        public string Email { get; set; }

        [DataType(DataType.Password)]
        [RegularExpression(@"(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,}$", ErrorMessage = "Must contain at least one number and one uppercase and lowercase letter, and at least 8 or more characters.")]
        [Required(ErrorMessage = "Password is Required")]
        public string Password { get; set; }

        [Required(ErrorMessage = "Mobile Number is Required")]
        [RegularExpression(@"[0-9]{10}$", ErrorMessage = "Mobile Number should contain 10 digits only.")]
        public string Mobile_No { get; set; }

        [Required(ErrorMessage = "Deleivery Address is Required")]
        public string Delivery_Address { get; set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
